- name: "configuring local machine for ansible"
  hosts: local
  become: true
  vars:
    - gitdir: "/tmp/addressbook-project-1"
  tasks:
    - name: "install maven"
      apt:
        name: "maven"
        state: "present"
    - name: "clone git repository"
      ansible.builtin.git:
        repo: "https://github.com/Shaileshmsk/addressbook.git"
        dest: "{{ gitdir }}"
        version: "master"
    - name: "compile the addressbook"
      command:
        chdir: "{{ gitdir }}"
        cmd: "mvn package"

- name: "setup webserver and depoly WAR"
  hosts: webserver
  become: true
  vars:
    gitdir: "/tmp/addressbook-project-1"
  tasks:
    - name: "install tomcat9"
      apt:
        name: tomcat9
      notify: "enable tomcat service"
    - name: "deply WAR file"
      copy:
        src: "{{ gitdir }}//target/addressbook-2.0.war"
        dest: "/var/lib/tomcat9/webapps/addressbook.war"
      notify: "restart tomcat service post deployment"
  handlers:
    - name: "enable tomcat service"
      service:
        name: tomcat9
        state: started
        enabled: yes
    - name: "restart tomcat service post deployment"
      service:      
        name: tomcat9
        state: restarted

      

